name: dust
channels:
  - bioconda
  - conda-forge
dependencies:
  - numpy
  - xarray=2022.*
  - pandas
  - python=3.10
  - matplotlib
  - scipy
  - netcdf4
  - cartopy
  - dask=2022.*
  - dask_jobqueue=0.8.*
  - zarr=2.13.* 
  - snakemake=7.20
  - pip
  - pip:
      - "--editable=git+https://github.com/MasterOnDust/Thesis_toolbox#egg=Thesis_toolbox"
      - "--editable=git+https://github.com/MasterOnDust/DUST#egg=DUST"
      
