
#####################################################################################
# Workflow for processing FLEXPART/FLEXDUST model output, for doing analysis        # 
# with regards to the "Tracing the winds" project and master thesis with working    #
# title "Aeolian dust sources, transport and deposition over the Chinese            #
# Loess Plateau during 1999-2019: A study using the FLEXDUST and FLEXPART models    # 
# by Ove Haugvaldstad et al"                                                        #
# Include rules processing and downloading ERA5 data                                # 
#                                                                                   # 
# Created by Ove Haugvaldstad, ovewh@student.geo.uio.no                             #
#                                                                                   # 
#####################################################################################

# Load config file

configfile: "config/config.yaml"

#----------------------------------CONSTANTS----------------------------------------#

import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import xarray as xr



wildcard_constraints:
    season='DJF|MAM',
    fig_file_extention='png|pdf',
    location='|'.join(config['receptors'].keys())+'|BAODE',
    region='|'.join(config['source_regions'].keys())+'|total',
    comp_type='std_anom|anom|std|comp_only',
    threshold='05-std|1-std|2-std'

include: 'rules/process_models_data_rules/process_emission_field.smk'
include: 'rules/process_models_data_rules/process_source_contribution.smk'
include: 'rules/process_models_data_rules/calc_total_deposition.smk'
include: 'rules/create_timeseries_table.smk'
include: 'rules/process_models_data_rules/trajectory_clustering.smk'
include: 'rules/get_dust_loading_trajectories.smk'

SDATE=config['sdate']
EDATE=config['edate']
MODEL_SDATE=config['m_sdate']
MODEL_EDATE=config['m_edate']
SEASONS=['DJF','MAM']

rule make_source_contrib_march:
    input:
        expand(config['source_contrib_path']+'/{kind}/{size}/{year}/{kind}_{location}_{tag}_{year}0301-{year}0331.zarr',
                kind=['drydep', 'wetdep'],location=['SACOL','LINGTAI','BAODE','SHAPOTOU','ULANTATAL', 'LANTIAN','LUOCHUAN'],
                size=['2micron'],tag=['CLAY'],
                year=[1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2011,2012,2013,2014,2015,2016,2017,2018,2019]),
        expand(config['source_contrib_path']+'/{kind}/{size}/{year}/{kind}_{location}_{tag}_{year}0301-{year}0331.zarr',
                kind=['drydep', 'wetdep'],location=['SACOL','LINGTAI','BAODE','SHAPOTOU','ULANTATAL', 'LANTIAN','LUOCHUAN'],
                size=['20micron'],tag=['SILT'],
                year=[1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2011,2012,2013,2014,2015,2016,2017,2018,2019])

rule make_source_contrib_apr:
    input:
        expand(config['source_contrib_path']+'/{kind}/{size}/{year}/{kind}_{location}_{tag}_{year}0331-{year}0430.zarr',
                kind=['drydep', 'wetdep'],location=['SACOL','LINGTAI','BAODE','SHAPOTOU','ULANTATAL', 'LANTIAN','LUOCHUAN'],
                size=['2micron'],tag=['CLAY'],
                year=[1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2011,2012,2013,2014,2015,2016,2017,2018,2019]),
        expand(config['source_contrib_path']+'/{kind}/{size}/{year}/{kind}_{location}_{tag}_{year}0331-{year}0430.zarr',
                kind=['drydep', 'wetdep'],location=['SACOL','LINGTAI','BAODE','SHAPOTOU','ULANTATAL', 'LANTIAN','LUOCHUAN'],
                size=['20micron'],tag=['SILT'],
                year=[1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2011,2012,2013,2014,2015,2016,2017,2018,2019])
rule make_source_contrib_may:
    input:
        expand(config['source_contrib_path']+'/{kind}/{size}/{year}/{kind}_{location}_{tag}_{year}0430-{year}0531.zarr',
        kind=['drydep', 'wetdep'],location=['SACOL','LINGTAI','BAODE','SHAPOTOU','ULANTATAL', 'LANTIAN','LUOCHUAN'],
                size=['2micron'],tag=['CLAY'],
                year=[1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2011,2012,2013,2014,2015,2016,2017,2018,2019]),
        expand(config['source_contrib_path']+'/{kind}/{size}/{year}/{kind}_{location}_{tag}_{year}0430-{year}0531.zarr',
        kind=['drydep', 'wetdep'],location=['SACOL','LINGTAI','BAODE','SHAPOTOU','ULANTATAL', 'LANTIAN','LUOCHUAN'],
                size=['20micron'],tag=['SILT'],
                year=[1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2011,2012,2013,2014,2015,2016,2017,2018,2019])



