# This file configures the workflow on a global scale.
# Setting the global path variables etss

# Setting different global paths where the result should be stored 
flexpart_path: "/cluster/work/users/ovewh/FLEXPART_updated_domain"
flexdust_path: "/cluster/work/users/ovewh/FLEXDUST1999_2019"
source_contrib_path: "/cluster/work/users/ovewh/source_contrib_1999_2019"
flexdust_results: "results/model_results/flexdust"
intermediate_results_models: "results/model_results/intermediate_results"
source_contrib_results: "results/model_results/source_contrib"

# Variables name used to constrain the wildcards

m_sdate: 1999
m_edate: 2019


# Domain for processing FLEXPART/FLEXDUST model output on
domain:
    lon0: 50
    lon1: 128
    lat0: 25
    lat1: 65

# Recepotor Location used in the procject.

receptors:
    SACOL:
        lon: 104.1370
        lat: 35.96400
    BAODE:
        lon: 111.1700
        lat: 39.00300
    LANTIAN:
        lon: 109.2560
        lat: 34.18000
    LINGTAI:
        lon: 107.7890
        lat: 35.71000 
    SHAPOTOU:
        lon: 105.0475
        lat: 34.18000
    ULANTATAL:
        lon: 105.53
        lat: 39.18
    LUOCHUAN:
        lat: 109.4240
        lon: 35.71000

source_regions:
        taklamakan:
            lon0: 75
            lon1: 90
            lat0: 36
            lat1: 42
        north_west:
            lon0: 100
            lon1: 110
            lat0: 37
            lat1: 42
        mongolia:
            lon0: 95
            lon1: 110
            lat0: 43
            lat1: 50
        jungger_basin:
            lon0: 80
            lon1: 90
            lat0: 43
            lat1: 47
        quaidam_basin:
            lon0: 90
            lon1: 100
            lat0: 35
            lat1: 40
        central_asia:
            lon0: 56
            lon1: 73
            lat0: 26
            lat1: 47        
